/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_17_primeiro_crud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author m.schmidt
 */
public class Tela_Delete extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Delete
     */
    public Tela_Delete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPNL_BackGround = new javax.swing.JPanel();
        JPNL_Informacoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JLBL_Deletar = new javax.swing.JLabel();
        JBN_Adiciona = new javax.swing.JButton();
        JBN_Procura = new javax.swing.JButton();
        JBN_Edita = new javax.swing.JButton();
        JBN_Delete = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(430, 450));
        setPreferredSize(new java.awt.Dimension(400, 400));

        JPNL_BackGround.setBackground(new java.awt.Color(255, 255, 255));
        JPNL_BackGround.setInheritsPopupMenu(true);
        JPNL_BackGround.setMaximumSize(new java.awt.Dimension(400, 400));
        JPNL_BackGround.setMinimumSize(new java.awt.Dimension(400, 400));
        JPNL_BackGround.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("DELETAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("ID:");

        javax.swing.GroupLayout JPNL_InformacoesLayout = new javax.swing.GroupLayout(JPNL_Informacoes);
        JPNL_Informacoes.setLayout(JPNL_InformacoesLayout);
        JPNL_InformacoesLayout.setHorizontalGroup(
            JPNL_InformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPNL_InformacoesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(JPNL_InformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(JPNL_InformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                        .addComponent(jTextField1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        JPNL_InformacoesLayout.setVerticalGroup(
            JPNL_InformacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPNL_InformacoesLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addContainerGap())
        );

        JPNL_BackGround.add(JPNL_Informacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 360, 150));

        JLBL_Deletar.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JLBL_Deletar.setForeground(new java.awt.Color(0, 0, 0));
        JLBL_Deletar.setText("DELETAR");
        JPNL_BackGround.add(JLBL_Deletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        JBN_Adiciona.setText("ADICIONA");
        JBN_Adiciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_AdicionaActionPerformed(evt);
            }
        });
        JPNL_BackGround.add(JBN_Adiciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        JBN_Procura.setText("PROCURA");
        JBN_Procura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_ProcuraActionPerformed(evt);
            }
        });
        JPNL_BackGround.add(JBN_Procura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        JBN_Edita.setText("EDITA");
        JBN_Edita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_EditaActionPerformed(evt);
            }
        });
        JPNL_BackGround.add(JBN_Edita, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        JBN_Delete.setText("DELETE");
        JBN_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_DeleteActionPerformed(evt);
            }
        });
        JPNL_BackGround.add(JBN_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNL_BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPNL_BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                try {
            // TODO add your handling code here:

            Connection conexao = null;
            PreparedStatement statement = null;

            String url = "jdbc:mysql://127.0.0.1:3306/crud";
            String usuario = "root";
            String senha = "";

            conexao = DriverManager.getConnection(url, usuario, senha);

            String sql = "DELETE FROM cadastro WHERE id = ?";

            statement = conexao.prepareStatement(sql);

            statement.setString(1, jTextField1.getText()); //ID
            
            statement.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Delete.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void JBN_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBN_DeleteActionPerformed

    private void JBN_ProcuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_ProcuraActionPerformed
        // TODO add your handling code here:
        Tela_Delete.this.dispose();
        Tela_Read Tela_Read = new Tela_Read();
        Tela_Read.setVisible(true);
    }//GEN-LAST:event_JBN_ProcuraActionPerformed

    private void JBN_EditaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_EditaActionPerformed
        // TODO add your handling code here:
        Tela_Delete.this.dispose();
        Tela_Update Tela_Update = new Tela_Update();
        Tela_Update.setVisible(true);
    }//GEN-LAST:event_JBN_EditaActionPerformed

    private void JBN_AdicionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_AdicionaActionPerformed
        // TODO add your handling code here:
        Tela_Delete.this.dispose();
        Tela_Create Tela_Create = new Tela_Create();
        Tela_Create.setVisible(true);
    }//GEN-LAST:event_JBN_AdicionaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Delete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Delete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBN_Adiciona;
    private javax.swing.JButton JBN_Delete;
    private javax.swing.JButton JBN_Edita;
    private javax.swing.JButton JBN_Procura;
    private javax.swing.JLabel JLBL_Deletar;
    private javax.swing.JPanel JPNL_BackGround;
    private javax.swing.JPanel JPNL_Informacoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
