/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projeto_17_primeiro_crud;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author m.schmidt
 */
public class Tela_Create extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Create
     */
    public Tela_Create() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLB_Cadastro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JTextF_Nome = new javax.swing.JTextField();
        JTextF_Sobrenome = new javax.swing.JTextField();
        JTextF_CPF = new javax.swing.JTextField();
        JBN_Adicionar = new javax.swing.JButton();
        JTextF_Numero = new javax.swing.JTextField();
        JBL_Nome = new javax.swing.JLabel();
        JBL_Sobrenome = new javax.swing.JLabel();
        JBL_CPF = new javax.swing.JLabel();
        JBL_Numero = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 400));
        setMinimumSize(new java.awt.Dimension(400, 400));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 400));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLB_Cadastro.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        JLB_Cadastro.setForeground(new java.awt.Color(0, 0, 0));
        JLB_Cadastro.setText("CADASTRO");
        jPanel1.add(JLB_Cadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 120, -1));

        jPanel2.setMaximumSize(new java.awt.Dimension(400, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(400, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(JTextF_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 230, -1));
        jPanel2.add(JTextF_Sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, -1));
        jPanel2.add(JTextF_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, -1));

        JBN_Adicionar.setBackground(new java.awt.Color(51, 255, 51));
        JBN_Adicionar.setText("Adicionar");
        JBN_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBN_AdicionarActionPerformed(evt);
            }
        });
        jPanel2.add(JBN_Adicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));
        jPanel2.add(JTextF_Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 230, -1));

        JBL_Nome.setText("Nome:");
        jPanel2.add(JBL_Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        JBL_Sobrenome.setText("Sobrenome:");
        jPanel2.add(JBL_Sobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        JBL_CPF.setText("CPF:");
        jPanel2.add(JBL_CPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        JBL_Numero.setText("Celular:");
        jPanel2.add(JBL_Numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 360, 220));

        jButton1.setText("ADICIONAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jButton2.setText("PROCURAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, -1, -1));

        jButton3.setText("EDITAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBN_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBN_AdicionarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection conexao = null;
            PreparedStatement statement = null;

            String url = "jdbc:mysql://127.0.0.1:3306/crud";
            String usuario = "root";
            String senha = "";

            conexao = DriverManager.getConnection(url, usuario, senha);
            String sql = "INSERT INTO cadastro (Nome,Sobrenome,CPF,Numero) "
                    + "VALUES (?, ?, ?, ?)";
            statement = conexao.prepareStatement(sql);
            statement.setString(1, JTextF_Nome.getText()); //Nome
            statement.setString(2, JTextF_Sobrenome.getText()); //Sobrenome
            statement.setString(3, JTextF_CPF.getText()); //CPF
            statement.setString(4, JTextF_Numero.getText()); //Numero

            statement.executeUpdate();
            System.out.println("Você foi Cadastrado");
        } catch (SQLException ex) {
            System.out.println("Erro no codigo" + ex.getMessage());
        }
    }//GEN-LAST:event_JBN_AdicionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Tela_Create.this.dispose();
        Tela_Read Tela_Read = new Tela_Read();
        Tela_Read.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Tela_Create.this.dispose();
        Tela_Update Tela_Update = new Tela_Update();
        Tela_Update.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Tela_Create.this.dispose();
        Tela_Delete Tela_Delete = new Tela_Delete();
        Tela_Delete.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JBL_CPF;
    private javax.swing.JLabel JBL_Nome;
    private javax.swing.JLabel JBL_Numero;
    private javax.swing.JLabel JBL_Sobrenome;
    private javax.swing.JButton JBN_Adicionar;
    private javax.swing.JLabel JLB_Cadastro;
    private javax.swing.JTextField JTextF_CPF;
    private javax.swing.JTextField JTextF_Nome;
    private javax.swing.JTextField JTextF_Numero;
    private javax.swing.JTextField JTextF_Sobrenome;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
